services:
    # Base Transformers
    AppBundle\Form\Transformer\:
        resource: '../../../src/AppBundle/Form/Transformer/*'
    
    # Entity Transformers
    app.form.transformer.advert_2_number:
        class: AppBundle\Form\Transformer\EntityToNumberTransformer
        arguments: ['@AppBundle\Repository\Admin\Main\AdvertRepository']
        tags:
            - { name: form.transformer }
    app.form.transformer.article_category_2_number:
        class: AppBundle\Form\Transformer\EntityToNumberTransformer
        arguments: ['@AppBundle\Repository\Admin\Main\ArticleCategoryRepository']
        tags:
            - { name: form.transformer }
    app.form.transformer.article_2_number:
        class: AppBundle\Form\Transformer\EntityToNumberTransformer
        arguments: ['@AppBundle\Repository\Admin\Main\ArticleRepository']
        tags:
            - { name: form.transformer }
    app.form.transformer.branch_2_number:
        class: AppBundle\Form\Transformer\EntityToNumberTransformer
        arguments: ['@AppBundle\Repository\Admin\Main\BranchRepository']
        tags:
            - { name: form.transformer }
    app.form.transformer.brand_2_number:
        class: AppBundle\Form\Transformer\EntityToNumberTransformer
        arguments: ['@AppBundle\Repository\Admin\Main\BrandRepository']
        tags:
            - { name: form.transformer }
    app.form.transformer.category_2_number:
        class: AppBundle\Form\Transformer\EntityToNumberTransformer
        arguments: ['@AppBundle\Repository\Admin\Main\CategoryRepository']
        tags:
            - { name: form.transformer }
    app.form.transformer.link_2_number:
        class: AppBundle\Form\Transformer\EntityToNumberTransformer
        arguments: ['@AppBundle\Repository\Admin\Main\LinkRepository']
        tags:
            - { name: form.transformer }
    app.form.transformer.magazine_2_number:
        class: AppBundle\Form\Transformer\EntityToNumberTransformer
        arguments: ['@AppBundle\Repository\Admin\Main\MagazineRepository']
        tags:
            - { name: form.transformer }
    app.form.transformer.menu_entry_2_number:
        class: AppBundle\Form\Transformer\EntityToNumberTransformer
        arguments: ['@AppBundle\Repository\Admin\Main\MenuEntryRepository']
        tags:
            - { name: form.transformer }
    app.form.transformer.menu_2_number:
        class: AppBundle\Form\Transformer\EntityToNumberTransformer
        arguments: ['@AppBundle\Repository\Admin\Main\MenuRepository']
        tags:
            - { name: form.transformer }
    app.form.transformer.newsletter_block_2_number:
        class: AppBundle\Form\Transformer\EntityToNumberTransformer
        arguments: ['@AppBundle\Repository\Admin\Main\NewsletterBlockRepository']
        tags:
            - { name: form.transformer }
    app.form.transformer.newsletter_block_template_2_number:
        class: AppBundle\Form\Transformer\EntityToNumberTransformer
        arguments: ['@AppBundle\Repository\Admin\Main\NewsletterBlockTemplateRepository']
        tags:
            - { name: form.transformer }
    app.form.transformer.newsletter_group_2_number:
        class: AppBundle\Form\Transformer\EntityToNumberTransformer
        arguments: ['@AppBundle\Repository\Admin\Main\NewsletterGroupRepository']
        tags:
            - { name: form.transformer }
    app.form.transformer.newsletter_page_2_number:
        class: AppBundle\Form\Transformer\EntityToNumberTransformer
        arguments: ['@AppBundle\Repository\Admin\Main\NewsletterPageRepository']
        tags:
            - { name: form.transformer }
    app.form.transformer.newsletter_page_template_2_number:
        class: AppBundle\Form\Transformer\EntityToNumberTransformer
        arguments: ['@AppBundle\Repository\Admin\Main\NewsletterPageTemplateRepository']
        tags:
            - { name: form.transformer }
    app.form.transformer.newsletter_user_2_number:
        class: AppBundle\Form\Transformer\EntityToNumberTransformer
        arguments: ['@AppBundle\Repository\Admin\Main\NewsletterUserRepository']
        tags:
            - { name: form.transformer }
    app.form.transformer.page_2_number:
        class: AppBundle\Form\Transformer\EntityToNumberTransformer
        arguments: ['@AppBundle\Repository\Admin\Main\PageRepository']
        tags:
            - { name: form.transformer }
    app.form.transformer.product_2_number:
        class: AppBundle\Form\Transformer\EntityToNumberTransformer
        arguments: ['@AppBundle\Repository\Admin\Main\ProductRepository']
        tags:
            - { name: form.transformer }
    app.form.transformer.segment_2_number:
        class: AppBundle\Form\Transformer\EntityToNumberTransformer
        arguments: ['@AppBundle\Repository\Admin\Main\SegmentRepository']
        tags:
            - { name: form.transformer }
    app.form.transformer.tag_2_number:
        class: AppBundle\Form\Transformer\EntityToNumberTransformer
        arguments: ['@AppBundle\Repository\Admin\Main\TagRepository']
        tags:
            - { name: form.transformer }
    app.form.transformer.term_2_number:
        class: AppBundle\Form\Transformer\EntityToNumberTransformer
        arguments: ['@AppBundle\Repository\Admin\Main\TermRepository']
        tags:
            - { name: form.transformer }
    app.form.transformer.user_2_number:
        class: AppBundle\Form\Transformer\EntityToNumberTransformer
        arguments: ['@AppBundle\Repository\Admin\Main\UserRepository']
        tags:
            - { name: form.transformer }