AppBundle\Entity\Advert:
    properties:
        name:
            - NotBlank: ~
        location:
            - Range:
                min: 0
                max: 99
        showLimit:
            - Range:
                min: 0
                max: 9999999
        clickLimit:
            - Range:
                min: 0
                max: 9999999   