AppBundle\Entity\ArticleCategoryAssignment:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: [article, category]
            errorPath: category
            ignoreNull: false
            message: 'articleCategoryAssignment.unique'
        - Callback: validate     