AppBundle\Entity\Brand:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: name
    properties:
        name:
            - NotBlank: ~
        products:
            - Count:
                groups: [removal]
                max: 0
                exactMessage: brand.usedIn.products          