AppBundle\Entity\MenuEntryCategoryAssignment:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: [menuEntry, category]
            ignoreNull: false
            message: 'menuEntryCategoryAssignment.unique'
                