AppBundle\Entity\NewsletterGroup:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: name
    properties:
        name:
            - NotBlank: ~
        id:
            - Range:
                groups: [removal]
                min: 3
                minMessage: newsletterGroup.cannotDelete
        newsletterUserNewsletterGroupAssignments:
            - Count:
                groups: [removal]
                max: 0
                exactMessage: newsletterGroup.usedIn.newsletterUserNewsletterGroupAssignments