AppBundle\Entity\NewsletterBlockMagazineAssignment:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: [newsletterBlock, magazine]
            errorPath: magazine
            ignoreNull: false
            message: 'newsletterBlockMagazineAssignment.unique'
                